language: python
cache: pip
python:
  - '3.7'
  - '3.8'
  - '3.9'
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pylama ttls
  - poetry run isort --check ttls
  - poetry run black --check ttls
notifications:
  email: false
